In [4]:
a = [1, 3.5, "Hello"] 
a

[1, 3.5, 'Hello']

In [5]:
import array as arr

In [6]:
a = arr.array('d', [1, 3.5, "Hello"]) 

TypeError: must be real number, not str

In [7]:
a1 = arr.array('i', [2, 4, 6, 8])
a1

array('i', [2, 4, 6, 8])

In [8]:
a1[0]

2

In [9]:
numbers_list = [2, 5, 62, 5, 42, 52, 48, 5]
numbers_array = arr.array('i', numbers_list)
numbers_list

[2, 5, 62, 5, 42, 52, 48, 5]

In [10]:
numbers_array

array('i', [2, 5, 62, 5, 42, 52, 48, 5])

In [11]:
numbers_array[0:3]

array('i', [2, 5, 62])

In [12]:
numbers_array[1]=77
numbers_array

array('i', [2, 77, 62, 5, 42, 52, 48, 5])

In [13]:
numbers_array[2:5] = arr.array('i', [4, 6, 8])

In [14]:
numbers_array

array('i', [2, 77, 4, 6, 8, 52, 48, 5])

In [15]:
numbers_array.append(11)
numbers_array

array('i', [2, 77, 4, 6, 8, 52, 48, 5, 11])

In [16]:
numbers_array.extend([10,20,30])
numbers_array

array('i', [2, 77, 4, 6, 8, 52, 48, 5, 11, 10, 20, 30])

In [17]:
del numbers_array[11]
numbers_array

array('i', [2, 77, 4, 6, 8, 52, 48, 5, 11, 10, 20])

In [18]:
numbers_array.remove(11)
numbers_array

array('i', [2, 77, 4, 6, 8, 52, 48, 5, 10, 20])

In [19]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
A

[[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]

In [20]:
A[0][1]

4

In [21]:
#numpy array
import numpy as np

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b=np.array([[1,2,3,4],[4,5,6,7,7]])
b

array([list([1, 2, 3, 4]), list([4, 5, 6, 7, 7])], dtype=object)

In [24]:
c=np.arange(12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
d=np.arange(10).reshape(5,2)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
p=np.array([[2,5],[1,3]])
q=np.array([[8,9],[7,8]])
p+q

array([[10, 14],
       [ 8, 11]])

In [27]:
p.dot(q)

array([[51, 58],
       [29, 33]])

In [28]:
dt = np.dtype(np.int32) 
dt

dtype('int32')

In [29]:
dt = np.dtype('i4')
dt 

dtype('int32')

In [30]:
x = np.array([1,2,3,4,5]) 
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [31]:
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
x

array([0., 1., 2., 3., 4.])

In [32]:
x = np.arange(5) 
x

array([0, 1, 2, 3, 4])

In [33]:
x = np.arange(10,21,2) 
x

array([10, 12, 14, 16, 18, 20])

In [34]:
x = np.linspace(10,20,5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [35]:
x = np.linspace(10,20,5 ,endpoint = False) 
x

array([10., 12., 14., 16., 18.])

In [36]:
a = np.logspace(1.0, 2.0, num = 10) 
a

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [37]:
a = np.arange(10) 
s = slice(2,8,1) 
a[s]

array([2, 3, 4, 5, 6, 7])

In [38]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y

array([1, 4, 5])

In [39]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[2,1,0], [0,1,0]] 
x
y

array([5, 4, 1])

In [40]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
'Our array is:' 
x 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
y

array([[ 0,  2],
       [ 9, 11]])

In [43]:
z = x[1:3,1:3] 
z

array([[4, 5],
       [7, 8]])

In [45]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [46]:
b = a.T
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [57]:
c = b.copy(order = 'C')
c

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [58]:
for x in np.nditer(c):
    print(x)
    
print ('\n')

0
20
40
5
25
45
10
30
50
15
35
55




In [60]:
c = b.copy(order = 'F')
for x in np.nditer(c,order = 'C'):
    print (x)

0
20
40
5
25
45
10
30
50
15
35
55


In [61]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [62]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


In [74]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [75]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)

int64


In [76]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

In [77]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
v

array([1, 0, 1])

In [79]:
y

array([[29310368,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0]])

In [80]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [81]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [82]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1)) 
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [83]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
